In [2]:
import torch
import torch.nn as nn

In [3]:
a = torch.tensor([
    [1, 2, 4, 5, 6],
])

bos = 10
eos = 11

b = torch.cat((torch.tensor([[bos]]), a, torch.tensor([[eos]])), dim=1)
b

tensor([[10,  1,  2,  4,  5,  6, 11]])

In [4]:
loss = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)
output = loss(input, target)
print(input.shape, input)
print(target.shape, target)
print(output)

torch.Size([3, 5]) tensor([[ 0.2940, -0.6474, -0.2855, -0.8119,  1.0651],
        [-0.3707,  0.4073, -0.6085, -2.9856,  1.8633],
        [ 1.0178, -0.4944, -0.2255, -0.3667,  1.2680]], requires_grad=True)
torch.Size([3]) tensor([4, 4, 3])
tensor(1.1924, grad_fn=<NllLossBackward0>)


In [5]:
l = nn.CrossEntropyLoss()

y_pred = torch.tensor([
    [0, 1],
    [1, 0],
    [0, 1],
], dtype=torch.float64).log()


y_true = torch.tensor([
    1,
    0,
    1
], dtype=torch.long)

print(y_pred.shape)
print(y_true.shape)
l(y_pred, y_true)

torch.Size([3, 2])
torch.Size([3])


tensor(0., dtype=torch.float64)

In [6]:
a = torch.tensor([
    [[1, 2, 3, 4], [1, 2, 3, 4]],
    [[2, 3, 4, 5], [2, 3, 4, 5]]
])

b = torch.tensor([
    [[10, 11, 12], [15, 16, 17]],
    [[20, 21, 22], [20, 21, 22]]
])

c = torch.cat((a, b), dim=-1)
print(a.shape, b.shape, c.shape)
print(c)

torch.Size([2, 2, 4]) torch.Size([2, 2, 3]) torch.Size([2, 2, 7])
tensor([[[ 1,  2,  3,  4, 10, 11, 12],
         [ 1,  2,  3,  4, 15, 16, 17]],

        [[ 2,  3,  4,  5, 20, 21, 22],
         [ 2,  3,  4,  5, 20, 21, 22]]])


In [8]:
l = nn.NLLLoss()

pred = torch.tensor([
    [0.2, 0.2, 0.6],
    [0.3, 0.2, 0.5],
]).log()

gold = torch.tensor([
    0,
    2
])

l(pred, gold)

tensor(1.1513)

In [ ]:
torch.tensor([
    [
        [1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10]
    ],
    [
        [1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10]
    ],
], dtype=torch.float64).mean(dim=1)

tensor([[3.5000, 4.5000, 5.5000, 6.5000, 7.5000],
        [3.5000, 4.5000, 5.5000, 6.5000, 7.5000]], dtype=torch.float64)

In [ ]:
a = torch.tensor(
    [
        [.2, .2, .2],
        [.0, .3, .3]
    ]
)

b = torch.tensor([
    [0,0,0],
    [1,1,0]
])

torch.where(b > 0, a, -1)

NameError: name 'torch' is not defined