In [5]:
import torch
import torch.nn as nn

In [2]:
a = torch.tensor([
    [1, 2, 4, 5, 6],
])

bos = 10
eos = 11

b = torch.cat((torch.tensor([[bos]]), a, torch.tensor([[eos]])), dim=1)
b

tensor([[10,  1,  2,  4,  5,  6, 11]])

In [3]:
loss = nn.CrossEntropyLoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.empty(3, dtype=torch.long).random_(5)
output = loss(input, target)
print(input.shape, input)
print(target.shape, target)
print(output)

torch.Size([3, 5]) tensor([[-0.7534, -1.0710,  0.8329,  0.7657,  0.6517],
        [-1.4071, -0.0265,  0.9603,  0.7727, -0.8400],
        [-0.6316, -0.4739,  0.0665, -0.1217, -0.7048]], requires_grad=True)
torch.Size([3]) tensor([1, 3, 0])
tensor(2.0147, grad_fn=<NllLossBackward0>)


In [4]:
l = nn.CrossEntropyLoss()

y_pred = torch.tensor([
    [0, 1],
    [1, 0],
    [0, 1],
], dtype=torch.float64).log()


y_true = torch.tensor([
    1,
    0,
    1
], dtype=torch.long)

print(y_pred.shape)
print(y_true.shape)
l(y_pred, y_true)

torch.Size([3, 2])
torch.Size([3])


tensor(0., dtype=torch.float64)

In [5]:
a = torch.tensor([
    [[1, 2, 3, 4], [1, 2, 3, 4]],
    [[2, 3, 4, 5], [2, 3, 4, 5]]
])

b = torch.tensor([
    [[10, 11, 12], [15, 16, 17]],
    [[20, 21, 22], [20, 21, 22]]
])

c = torch.cat((a, b), dim=-1)
print(a.shape, b.shape, c.shape)
print(c)

torch.Size([2, 2, 4]) torch.Size([2, 2, 3]) torch.Size([2, 2, 7])
tensor([[[ 1,  2,  3,  4, 10, 11, 12],
         [ 1,  2,  3,  4, 15, 16, 17]],

        [[ 2,  3,  4,  5, 20, 21, 22],
         [ 2,  3,  4,  5, 20, 21, 22]]])


In [6]:
l = nn.NLLLoss()

pred = torch.tensor([
    [0.2, 0.2, 0.6],
    [0.3, 0.2, 0.5],
]).log()

gold = torch.tensor([
    0,
    2
])

l(pred, gold)

tensor(1.1513)

In [7]:
torch.tensor([
    [
        [1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10]
    ],
    [
        [1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10]
    ],
], dtype=torch.float64).mean(dim=1)

tensor([[3.5000, 4.5000, 5.5000, 6.5000, 7.5000],
        [3.5000, 4.5000, 5.5000, 6.5000, 7.5000]], dtype=torch.float64)

In [8]:
a = torch.tensor(
    [
        [.2, .2, .2],
        [.0, .3, .3]
    ]
)

b = torch.tensor([
    [0,0,0],
    [1,1,0]
])

torch.where(b > 0, a, -1)

tensor([[-1.0000, -1.0000, -1.0000],
        [ 0.0000,  0.3000, -1.0000]])

In [9]:
batch_size = 2
hidden_size = 3

a = torch.tensor(
    [
        [[0.1, .5, 0.9], [0.3, 0.7, 1.0], [0.0, 0.0, 0.0]],
        [[0.1, .5, 0.9], [0.3, 0.7, 1.0], [0.1, 0.1, 0.1]],
    ]
)

b = torch.tensor([[1, 1, 0], [1, 1, 1]])

c = torch.zeros((batch_size, hidden_size), dtype=torch.float32)

for i in range(a.shape[0]):
    values = a[i]
    attention = b[i]
    filtered = torch.zeros((hidden_size,))
    count = 0
    for j in range(a.shape[1]):
        if attention[j].item() == 1:
            filtered += values[j]
            count += 1
    filtered = filtered / count
    c[i] = filtered

c

tensor([[0.2000, 0.6000, 0.9500],
        [0.1667, 0.4333, 0.6667]])

In [10]:
batch_size = 2
hidden_size = 3

a = torch.tensor(
    [
        [[0.1, .5, 0.9], [0.3, 0.7, 1.0], [0.0, 0.0, 0.0]],
        [[0.1, .5, 0.9], [0.3, 0.7, 1.0], [0.1, 0.1, 0.1]],
    ]
)

b = torch.tensor([[1, 1, 0], [1, 1, 1]])

filter = b.reshape(2, 3, 1).expand(2, 3, 3)

c = torch.where(filter > 0, a, 0)

l = b.sum(dim=1).reshape(-1, 1)
s = c.sum(dim=1)
s / l

tensor([[0.2000, 0.6000, 0.9500],
        [0.1667, 0.4333, 0.6667]])

In [4]:
cp = torch.load("checkpoints/charlm_256_1_fullvocab/best.pt")

print(cp["report"])

              precision    recall  f1-score   support

           0       0.59      0.83      0.69      2500
           1       0.72      0.43      0.54      2500

    accuracy                           0.63      5000
   macro avg       0.66      0.63      0.62      5000
weighted avg       0.66      0.63      0.62      5000



In [ ]:
a = {"a": 1}
b = {"b": 2}
c = {"a": 3}

{**a, **b, **c}

: 

In [6]:
a = torch.tensor(
    [
        [[0.1, .5, 0.9], [0.3, 0.7, 1.0], [0.0, 0.0, 11.0]],
        [[0.1, .5, 0.9], [0.3, 0.7, 1.0], [0.1, 0.1, 0.1]],
        [[0.1, .5, 0.9], [0.3, 0.7, 1.0], [0.1, 0.1, 12.0]],
    ]
)

b = a[[0, 2], :, :]
b

tensor([[[ 0.1000,  0.5000,  0.9000],
         [ 0.3000,  0.7000,  1.0000],
         [ 0.0000,  0.0000, 11.0000]],

        [[ 0.1000,  0.5000,  0.9000],
         [ 0.3000,  0.7000,  1.0000],
         [ 0.1000,  0.1000, 12.0000]]])